spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
    default-schema: "tastboot"
  datasource:
    hikari:
      jdbc-url: "jdbc:mysql://localhost:3306/ItAcademy"
      maximum-pool-size: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root
    url: "jdbc:mysql://localhost:3306/ItAcademy"
server:
  port: 8081